#!/usr/bin/env php
<?php
require_once __DIR__ . '/../vendor/autoload.php';

use Symfony\Component\Console\Application;
use Martin1982\Command\CalculatorCommand;

$command = new CalculatorCommand();

$app = new Application();
$app->add($command);
$app->run();
